[package]
name = "zero_trust_gateway"
version = "0.1.0"
edition = "2024"
authors = ["Phung The Vinh <ptvstar2003@gmail.com>"]
license-file = "LICENSE"
publish = false


[dependencies]
tokio = { version = "1.52.3", features = ["full"] }
axum = { version = "0.8.9", features = ["macros"] }
hyper = { version = "1.4.1", features = ["full"] }
tower = { version = "0.4.13", features = ["util"] }
tower-http = { version = "0.5.2", features = ["fs", "trace", "cors"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
jsonwebtoken = { version = "10.4.0", features = ["rust_crypto"] }
ring = { version = "0.17", features = ["alloc"] }
moka = { version = "0.12.8", features = ["future"] }
redis = { version = "1.2.2", features = ["tokio-comp"] }
reqwest = { version = "0.12", features = ["json", "stream"] }
tract-onnx = "0.21.3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1.8.0", features = ["v4"] }
chrono = "0.4.45"
base64 = "0.22"
serde_json = "1.0.151"
